# use Ganache's forked mainnet mode as the default network
# NOTE: You don't *have* to do this, but it is often helpful for testing
networks:
  default: ftm-main-fork

# automatically fetch contract sources from Etherscan
autofetch_sources: true

# require OpenZepplin Contracts
dependencies:
  - OpenZeppelin/openzeppelin-contracts@4.5.0
  - yearn/yearn-vaults@0.4.3

# path remapping to support imports from GitHub/NPM
compiler:
  solc:
    version: 0.8.11
    optimize: true
    runs: 200
    remappings:
      - '@openzeppelin=OpenZeppelin/openzeppelin-contracts@4.5.0'
      - '@yearnvaults=iearn-finance/yearn-vaults@0.4.3'

reports:
  exclude_contracts:
    - SafeMath
